name: Conda-Forge Workflow

on:
  push:
    branches:
      - main  # Modify this if your default branch is different
  pull_request:
    branches:
      - main  # Modify this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Replace 'x' with the desired Python version

      - name: Install conda
        run: |
          wget -qO miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          bash miniconda.sh -b -p $HOME/miniconda
          source "$HOME/miniconda/etc/profile.d/conda.sh"
          conda activate base

      - name: Configure conda-forge
        run: |
          conda config --env --add channels conda-forge
          conda config --env --set channel_priority strict

      - name: Install packages
        run: |
          conda install --yes boule metpy package3  # Replace with the packages you want to install

      #- name: Run your code
      #  run: python your_script.py  # Replace with the command to run your Python code
